Updated the About Us page
TrickfireRobotics/TrickFire-Website pull request #34
Opened 2023-05-30 07:49 UTC by agrach060

I have updated about us page based on your comments. Please review

2023-05-31 09:58 UTC, adamseth2 commented
Make the title "Meet our team" bigger to increase hierarchy (Might do this later as this is a general design across all pages)


Not sure if this is intended to have the sub team's pic to be in 2 different cards: Maybe consider only having one and putting the Software Team Left align along with the description?
![image](https://github.com/TrickfireRobotics/TrickfireRobotics.github.io/assets/35408139/2c59f26e-a5e5-4d4a-bae8-df8f562a942b)


At 1001px view width, where it switches between mobile and desktop view, some of the text gets cut off Maybe increase the media query so this doesn't happen?
![image](https://github.com/TrickfireRobotics/TrickfireRobotics.github.io/assets/35408139/3c7fdccd-e044-472f-ae97-3d4e55c895eb)


Everything else looks good!

2023-05-31 10:31 UTC, adamseth2 requested changes
^

2023-06-03 19:25 UTC, agrach060 commented
I have increased the media query. As for the row blocks, I will be able to fix them after the content of this branch is pushed to dev.

2023-06-05 08:51 UTC, adamseth2 approved these changes

2023-06-07 18:32 UTC, merged